//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_Campaign_Project.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A611YRRQ90zVuVygqMagl/O1kDWRyBdeQyZJEomZlqI=")]
        public string MySQL_Host {
            get {
                return ((string)(this["MySQL_Host"]));
            }
            set {
                this["MySQL_Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7/K93P2WuMadeXsIYjWdA4WDdEIxpglppHcvxTCeJ/4=")]
        public string MySQL_Username {
            get {
                return ((string)(this["MySQL_Username"]));
            }
            set {
                this["MySQL_Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NSQx+wDxwZJK351IScI/sQ==")]
        public string MySQL_Password {
            get {
                return ((string)(this["MySQL_Password"]));
            }
            set {
                this["MySQL_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uniqueone_c88")]
        public string MySQL_Table {
            get {
                return ((string)(this["MySQL_Table"]));
            }
            set {
                this["MySQL_Table"] = value;
            }
        }
    }
}
